/**
 * Mock Auth Adapter — localStorage-backed authentication for MVP/prototyping.
 *
 * This is a drop-in replacement for `supabase.auth` that stores a session
 * in localStorage and validates against hardcoded demo credentials.
 *
 * ─── DEMO CREDENTIALS ─────────────────────────────────────────────────────
 * Email:    zyx@gmail.com
 * Password: xyz
 *
 * ─── SWAP GUIDE ───────────────────────────────────────────────────────────
 * Do NOT edit this file when re-enabling Supabase Auth.
 * Instead, edit lib/authAdapter.ts — that is the only file that needs to change.
 */

const DEMO_EMAIL = "zyx@gmail.com";
const DEMO_PASSWORD = "xyz";
const STORAGE_KEY = "bp_mock_session";
const MOCK_TOKEN = "mock-dev-token";

// ─── Types ─────────────────────────────────────────────────────────────────

export interface MockUser {
  id: string;
  email: string;
}

export interface MockSession {
  access_token: string;
  user: MockUser;
}

// ─── Helpers ───────────────────────────────────────────────────────────────

function buildSession(email: string): MockSession {
  return {
    access_token: MOCK_TOKEN,
    user: { id: "mock-user-001", email },
  };
}

function readFromStorage(): MockSession | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? (JSON.parse(raw) as MockSession) : null;
  } catch {
    return null;
  }
}

// ─── Mock Auth Adapter ─────────────────────────────────────────────────────

export const mockAuth = {
  /**
   * Read the persisted session from localStorage.
   * Mirrors: supabase.auth.getSession()
   */
  async getSession() {
    const session = readFromStorage();
    return { data: { session }, error: null };
  },

  /**
   * Validate demo credentials and persist a session on success.
   * Mirrors: supabase.auth.signInWithPassword()
   */
  async signInWithPassword(credentials: { email: string; password: string }) {
    const { email, password } = credentials;
    if (
      email.trim().toLowerCase() === DEMO_EMAIL &&
      password === DEMO_PASSWORD
    ) {
      const session = buildSession(email.trim().toLowerCase());
      localStorage.setItem(STORAGE_KEY, JSON.stringify(session));
      return { data: { session, user: session.user }, error: null };
    }
    return {
      data: { session: null, user: null },
      error: { message: "Invalid email or password." },
    };
  },

  /**
   * Clear the persisted session from localStorage.
   * Mirrors: supabase.auth.signOut()
   */
  async signOut() {
    if (typeof window !== "undefined") {
      localStorage.removeItem(STORAGE_KEY);
    }
    return { error: null };
  },

  /**
   * Subscribe to auth state changes.
   * Mirrors: supabase.auth.onAuthStateChange()
   *
   * In mock mode there are no real-time events (no server, no token refresh).
   * We fire the callback once with the current persisted state, then return a
   * no-op subscription. The AuthContext manually updates state on signIn/signOut
   * so the UI stays in sync without needing real events.
   */
  onAuthStateChange(
    callback: (event: string, session: MockSession | null) => void
  ) {
    const session = readFromStorage();
    // Defer to avoid calling setState during render
    setTimeout(() => callback("INITIAL_SESSION", session), 0);

    return {
      data: {
        subscription: {
          unsubscribe: () => {
            // No-op — nothing to clean up in mock mode
          },
        },
      },
    };
  },
};
